@startuml
'https://plantuml.com/sequence-diagram

autonumber

@startuml

class post_order {
    ..Properties..
    - DIMENSIONS
    - ast_tree
    - stack
    - out

    ..Methods..
    + post_order(formula : string) : string
    + main(formula : string)
}

class UnresolvedVariable << (E,red) Exception >> {
    ..Properties..
    - message

}
@enduml